# Generated by Django 3.2.4 on 2021-07-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210724_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='experience',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='goals',
            new_name='level',
        ),
    ]
