# Generated by Django 3.2.4 on 2021-07-24 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application',
            old_name='job_title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='job_application',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='date',
            field=models.DateField(verbose_name='Date Applied'),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='job_application',
            name='requirements',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='status',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('A', 'Applied'), ('B', 'In Progress'), ('C', 'Interview scheduled'), ('D', 'Interview complete'), ('E', 'Job Offer'), ('F', 'Incomplete'), ('G', 'Not Selected'), ('H', 'Unknown')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('job_app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.job_application')),
            ],
        ),
    ]
