# Generated by Django 3.2.4 on 2021-07-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
